// Generated by CoffeeScript 1.3.3

module.exports = function(socket) {
  var message;
  message = require('../models/message');
  return message.find({}, function(err, messages) {
    return socket.emit('send:name', {
      tweets: messages
    });
  });
};
